// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SimplyBooksAPI.Data;

#nullable disable

namespace SimplyBooksAPI.Migrations
{
    [DbContext(typeof(SimplyBooksAPIDbContext))]
    [Migration("20241005171202_UpdatedAuthorBooksThree")]
    partial class UpdatedAuthorBooksThree
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SimplyBooksAPI.Models.AuthorBooks", b =>
                {
                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.HasKey("AuthorId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("AuthorBooks");
                });

            modelBuilder.Entity("SimplyBooksAPI.Models.Authors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Favorite")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ta@ta.com",
                            Favorite = true,
                            FirstName = "Tomi",
                            LastName = "Adeyemi",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "ba@obama.com",
                            Favorite = true,
                            FirstName = "Barack",
                            LastName = "Obama",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Email = "hz@zinn.com",
                            Favorite = false,
                            FirstName = "Howard",
                            LastName = "Zinn",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Email = "at@thomas.com",
                            Favorite = false,
                            FirstName = "Angie",
                            LastName = "Thomas",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Email = "cw@whithead.com",
                            Favorite = false,
                            FirstName = "Colson",
                            LastName = "Whitehead",
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            Email = "mk@kendall.com",
                            Favorite = true,
                            FirstName = "Mikki",
                            LastName = "Kendall",
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            Email = "lm@lm.com",
                            Favorite = true,
                            FirstName = "L.L",
                            LastName = "McKinney",
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            Email = "jb@baldwin.com",
                            Favorite = false,
                            FirstName = "James",
                            LastName = "Baldwin",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("SimplyBooksAPI.Models.Books", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Sale")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("UserId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5266793f-b30e-4728-9fac-44ab14e18760"),
                            AuthorId = 2,
                            Description = "",
                            Image = "https://images-na.ssl-images-amazon.com/images/I/91+NBrXG-PL.jpg",
                            Price = "24.99",
                            Sale = false,
                            Title = "A Promised Land",
                            UserId = 1
                        },
                        new
                        {
                            Id = new Guid("d0ad06b3-d2c3-4aee-9c66-eacc5667e64c"),
                            AuthorId = 1,
                            Description = "",
                            Image = "https://images-na.ssl-images-amazon.com/images/I/A1agLFsWkOL.jpg",
                            Price = "12.99",
                            Sale = true,
                            Title = "Children of Blood and Bone",
                            UserId = 1
                        },
                        new
                        {
                            Id = new Guid("08b6c6ea-105f-40be-b928-d26c7b4af841"),
                            AuthorId = 3,
                            Description = "",
                            Image = "https://images-na.ssl-images-amazon.com/images/I/51529Lfc2ML.jpg",
                            Price = "30.00",
                            Sale = false,
                            Title = "A People's History of the United States of America",
                            UserId = 1
                        },
                        new
                        {
                            Id = new Guid("ff318bb1-d560-43e0-857f-97f97188991b"),
                            AuthorId = 4,
                            Description = "",
                            Image = "https://images-na.ssl-images-amazon.com/images/I/81rRRmZZvZL.jpg",
                            Price = "15.89",
                            Sale = false,
                            Title = "Concrete Rose",
                            UserId = 1
                        },
                        new
                        {
                            Id = new Guid("02a5c0e8-54ed-4aee-b639-2163d011a7e6"),
                            AuthorId = 5,
                            Description = "",
                            Image = "https://images-na.ssl-images-amazon.com/images/I/A1Cu4ywUeyL.jpg",
                            Price = "25.00",
                            Sale = true,
                            Title = "The Underground Railroad",
                            UserId = 1
                        },
                        new
                        {
                            Id = new Guid("06acaeaf-8949-43f3-8508-0dee86455182"),
                            AuthorId = 6,
                            Description = "",
                            Image = "https://res.cloudinary.com/bloomsbury-atlas/image/upload/w_360,c_scale/jackets/9781526622402.jpg",
                            Price = "12.99",
                            Sale = true,
                            Title = "Hood Feminism",
                            UserId = 1
                        },
                        new
                        {
                            Id = new Guid("63df79a8-f99e-4e90-b3d3-1cf0c03e70b7"),
                            AuthorId = 7,
                            Description = "",
                            Image = "https://images-na.ssl-images-amazon.com/images/I/81Uf1dTjfQL.jpg",
                            Price = "15.00",
                            Sale = false,
                            Title = "A Blade So Black",
                            UserId = 1
                        },
                        new
                        {
                            Id = new Guid("0138188e-86d4-440b-8bec-6497d28ed108"),
                            AuthorId = 7,
                            Description = "",
                            Image = "https://m.media-amazon.com/images/I/51BZdlchEsL.jpg",
                            Price = "14.99",
                            Sale = false,
                            Title = "A Dream So Dark",
                            UserId = 1
                        },
                        new
                        {
                            Id = new Guid("c8520aa8-27df-49d1-9bd8-d4c2f5102c5f"),
                            AuthorId = 8,
                            Description = "",
                            Image = "https://images-na.ssl-images-amazon.com/images/I/61GSqXVhhKL.jpg",
                            Price = "12.00",
                            Sale = false,
                            Title = "The Fire Next Time",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("SimplyBooksAPI.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "britnaygore268@gmail.com",
                            Name = "Britnay Gore",
                            Uid = "NdnbyDbtZTUYr9T0YH4YicxApXG2"
                        });
                });

            modelBuilder.Entity("SimplyBooksAPI.Models.AuthorBooks", b =>
                {
                    b.HasOne("SimplyBooksAPI.Models.Authors", "Author")
                        .WithMany("AuthorBooks")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimplyBooksAPI.Models.Books", "Book")
                        .WithMany("AuthorBooks")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("SimplyBooksAPI.Models.Authors", b =>
                {
                    b.HasOne("SimplyBooksAPI.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SimplyBooksAPI.Models.Books", b =>
                {
                    b.HasOne("SimplyBooksAPI.Models.Authors", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimplyBooksAPI.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SimplyBooksAPI.Models.Authors", b =>
                {
                    b.Navigation("AuthorBooks");
                });

            modelBuilder.Entity("SimplyBooksAPI.Models.Books", b =>
                {
                    b.Navigation("AuthorBooks");
                });
#pragma warning restore 612, 618
        }
    }
}
